# Generated by Django 5.1 on 2024-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
